ak2: backend: Support for detecting treble-enabled ROMs
to-do:
* Detect devices with separate vendor but not having treble enabled

Signed-off-by: Albert I <krascgq@outlook.co.id>
Signed-off-by: Raphiel Rollerscaperers <raphielscape@outlook.com>

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -97,12 +97,24 @@ if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.devicecheck)" == 1 ]; then
   fi;
 fi;
 
+if [ "$(file_getprop /system/build.prop ro.treble.enabled)" == "true" ]; then
+  ui_print "Treble bois~"
+  dtb=/tmp/anykernel/treble;
+else
+  ui_print="Oof, move to treble soon plz"
+  dtb=/tmp/anykernel/nontreble;
+fi;
+
 ui_print "Installing...";
 for i in $($bb --list); do
   $bb ln -s $bb /tmp/anykernel/bin/$i;
 done;
 if [ $? != 0 -o -z "$(ls /tmp/anykernel/bin)" ]; then
   abort "Recovery busybox setup failed. Aborting...";
+fi;
+cat /tmp/anykernel/kernel/Image.gz $dtb/*.dtb > /tmp/anykernel/Image.gz-dtb;
+if [ $? != "0" ]; then
+  abort "DTB append failed. Aborting...";
 fi;
 PATH="/tmp/anykernel/bin:$PATH" $bb ash /tmp/anykernel/anykernel.sh $2;
 if [ $? != "0" ]; then
